### ISSUE TITLE
Should be using || rather than &&

### ISSUE THREAD

**Issue by blackbear** [jrturton/NSJSONSerialization-NSNullRemoval#4]
```
    opt = opt || NSJSONReadingMutableContainers;
```

rather than

```
    opt = opt && NSJSONReadingMutableContainers;
```

The later only works if you already passed in that flag

Otherwise works great, thanks!

**Comment by jrturton** [comment]
Hello,

Please can you show me some sample code (ideally in the form of a failing unit test) to demonstrate this issue? Then I will add it to the set of tests and make the change. 

Thanks

Richard

**Comment by ecaselles** [comment]
As @blackbear says, calling the method with nil options fails:

``` Obj-C
NSDictionary *jsonDictionary = [NSJSONSerialization JSONObjectWithData:data options: kNilOptions error: &error removingNulls:YES ignoreArrays:YES];
```

The error says:
JSON parsing failed with: -[__NSCFDictionary removeObjectForKey:]: mutating method sent to immutable

The reason is because doing 0 && ... always returns 0, so the NSJSONReadingMutableContainers option is never applied.

**Comment by jrturton** [comment]
Closed from pull request
